{
    "name": "Account Payment Invoice Payment",
    "version": "11.0.1.0.5",
    "summary": "Add Security Settings for Invoice Payment Process",
    'license': 'AGPL-3',
    "depends": ['account', ],
    'author': 'erickalvino@gmail.com',
    'website': 'https://www.binasanprima.com',
    'data': ['security/kontra_bon.xml',
             'security/ir.model.access.csv',
             'data/kontra_bon_data.xml',
             'data/kontra_bon_sequence.xml',
             'wizard/select_invoices_wizard_view.xml',
             'wizard/bsp_kontrabon_print_view.xml',
             'wizard/ted_spb_xlsx.xml',
             'views/kontra_bon_views.xml',
             'views/kontra_bon_menus.xml',
	     'views/ted_bank_enh_spb.xml',
             'views/account_invoice_views.xml',
             'reports/kontra_bon_report_template.xml',
             'reports/kontra_bon_report.xml',
             'views/invoice_batch_process_view.xml'],
}
